#!/bin/bash

# Define key parameters
KEY_NAME="school"
KEY_SIZE=4096
PASSPHRASE="betty"

ssh-keygen -t rsa -b $KEY_SIZE -f $KEY_NAME -N "$PASSPHRASE" -q

echo "RSA key pair generated with private key named '$KEY_NAME'"
