#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx
REDIRECT_CONFIG="
server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
"
echo "$REDIRECT_CONFIG" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
echo "Nginx installed and redirection configured successfully!"

