#!/usr/bin/env bash
# Configure custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i '/listen 80 default_server;/a \
    error_page 404 /404.html; \
    location = /404.html { \
        root /var/www/html; \
        internal; \
    }' /etc/nginx/sites-enabled/default

sudo service nginx restart
